// Mocks generated by Mockito from annotations
// in tv_series/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i8;
import 'dart:convert' as _i27;
import 'dart:typed_data' as _i28;

import 'package:dartz/dartz.dart' as _i2;
import 'package:http/http.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;
import 'package:sqflite/sqflite.dart' as _i26;
import 'package:tv_series/common/failure.dart' as _i9;
import 'package:tv_series/data/datasources/db/database_helper.dart' as _i25;
import 'package:tv_series/data/datasources/movie_local_data_source.dart'
    as _i14;
import 'package:tv_series/data/datasources/movie_remote_data_source.dart'
    as _i12;
import 'package:tv_series/data/datasources/tv_local_data_source.dart' as _i23;
import 'package:tv_series/data/datasources/tv_remote_data_source.dart' as _i21;
import 'package:tv_series/data/models/movie_detail_model.dart' as _i3;
import 'package:tv_series/data/models/movie_model.dart' as _i13;
import 'package:tv_series/data/models/movie_table.dart' as _i15;
import 'package:tv_series/data/models/season_detail_model.dart' as _i5;
import 'package:tv_series/data/models/tv_detail_model.dart' as _i4;
import 'package:tv_series/data/models/tv_model.dart' as _i22;
import 'package:tv_series/data/models/tv_table.dart' as _i24;
import 'package:tv_series/domain/entities/movie.dart' as _i10;
import 'package:tv_series/domain/entities/movie_detail.dart' as _i11;
import 'package:tv_series/domain/entities/season_detail.dart' as _i20;
import 'package:tv_series/domain/entities/tv.dart' as _i18;
import 'package:tv_series/domain/entities/tv_detail.dart' as _i19;
import 'package:tv_series/domain/repositories/movie_repository.dart' as _i7;
import 'package:tv_series/domain/repositories/tv_repository.dart' as _i17;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieDetailResponse_1 extends _i1.SmartFake
    implements _i3.MovieDetailResponse {
  _FakeMovieDetailResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTVDetailResponse_2 extends _i1.SmartFake
    implements _i4.TVDetailResponse {
  _FakeTVDetailResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSeasonDetailResponse_3 extends _i1.SmartFake
    implements _i5.SeasonDetailResponse {
  _FakeSeasonDetailResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_4 extends _i1.SmartFake implements _i6.Response {
  _FakeResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamedResponse_5 extends _i1.SmartFake
    implements _i6.StreamedResponse {
  _FakeStreamedResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i7.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>> getNowPlayingMovies() =>
      (super.noSuchMethod(
        Invocation.method(#getNowPlayingMovies, []),
        returnValue:
            _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>.value(
              _FakeEither_0<_i9.Failure, List<_i10.Movie>>(
                this,
                Invocation.method(#getNowPlayingMovies, []),
              ),
            ),
      ) as _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>> getPopularMovies() =>
      (super.noSuchMethod(
        Invocation.method(#getPopularMovies, []),
        returnValue:
            _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>.value(
              _FakeEither_0<_i9.Failure, List<_i10.Movie>>(
                this,
                Invocation.method(#getPopularMovies, []),
              ),
            ),
      ) as _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>> getTopRatedMovies() =>
      (super.noSuchMethod(
        Invocation.method(#getTopRatedMovies, []),
        returnValue:
            _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>.value(
              _FakeEither_0<_i9.Failure, List<_i10.Movie>>(
                this,
                Invocation.method(#getTopRatedMovies, []),
              ),
            ),
      ) as _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, _i11.MovieDetail>> getMovieDetail(
    int? id,
  ) => (super.noSuchMethod(
    Invocation.method(#getMovieDetail, [id]),
    returnValue: _i8.Future<_i2.Either<_i9.Failure, _i11.MovieDetail>>.value(
      _FakeEither_0<_i9.Failure, _i11.MovieDetail>(
        this,
        Invocation.method(#getMovieDetail, [id]),
      ),
    ),
  ) as _i8.Future<_i2.Either<_i9.Failure, _i11.MovieDetail>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>> getMovieRecommendations(
    int? id,
  ) => (super.noSuchMethod(
    Invocation.method(#getMovieRecommendations, [id]),
    returnValue: _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>.value(
      _FakeEither_0<_i9.Failure, List<_i10.Movie>>(
        this,
        Invocation.method(#getMovieRecommendations, [id]),
      ),
    ),
  ) as _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>> searchMovies(
    String? query,
  ) => (super.noSuchMethod(
    Invocation.method(#searchMovies, [query]),
    returnValue: _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>.value(
      _FakeEither_0<_i9.Failure, List<_i10.Movie>>(
        this,
        Invocation.method(#searchMovies, [query]),
      ),
    ),
  ) as _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, String>> saveWatchlist(
    _i11.MovieDetail? movie,
  ) => (super.noSuchMethod(
    Invocation.method(#saveWatchlist, [movie]),
    returnValue: _i8.Future<_i2.Either<_i9.Failure, String>>.value(
      _FakeEither_0<_i9.Failure, String>(
        this,
        Invocation.method(#saveWatchlist, [movie]),
      ),
    ),
  ) as _i8.Future<_i2.Either<_i9.Failure, String>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, String>> removeWatchlist(
    _i11.MovieDetail? movie,
  ) => (super.noSuchMethod(
    Invocation.method(#removeWatchlist, [movie]),
    returnValue: _i8.Future<_i2.Either<_i9.Failure, String>>.value(
      _FakeEither_0<_i9.Failure, String>(
        this,
        Invocation.method(#removeWatchlist, [movie]),
      ),
    ),
  ) as _i8.Future<_i2.Either<_i9.Failure, String>>);

  @override
  _i8.Future<bool> isAddedToWatchlist(int? id) => (super.noSuchMethod(
    Invocation.method(#isAddedToWatchlist, [id]),
    returnValue: _i8.Future<bool>.value(false),
  ) as _i8.Future<bool>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>> getWatchlistMovies() =>
      (super.noSuchMethod(
        Invocation.method(#getWatchlistMovies, []),
        returnValue:
            _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>.value(
              _FakeEither_0<_i9.Failure, List<_i10.Movie>>(
                this,
                Invocation.method(#getWatchlistMovies, []),
              ),
            ),
      ) as _i8.Future<_i2.Either<_i9.Failure, List<_i10.Movie>>>);
}

/// A class which mocks [MovieRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSource extends _i1.Mock
    implements _i12.MovieRemoteDataSource {
  MockMovieRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i13.MovieModel>> getNowPlayingMovies() =>
      (super.noSuchMethod(
        Invocation.method(#getNowPlayingMovies, []),
        returnValue: _i8.Future<List<_i13.MovieModel>>.value(
          <_i13.MovieModel>[],
        ),
      ) as _i8.Future<List<_i13.MovieModel>>);

  @override
  _i8.Future<List<_i13.MovieModel>> getPopularMovies() => (super.noSuchMethod(
    Invocation.method(#getPopularMovies, []),
    returnValue: _i8.Future<List<_i13.MovieModel>>.value(<_i13.MovieModel>[]),
  ) as _i8.Future<List<_i13.MovieModel>>);

  @override
  _i8.Future<List<_i13.MovieModel>> getTopRatedMovies() => (super.noSuchMethod(
    Invocation.method(#getTopRatedMovies, []),
    returnValue: _i8.Future<List<_i13.MovieModel>>.value(<_i13.MovieModel>[]),
  ) as _i8.Future<List<_i13.MovieModel>>);

  @override
  _i8.Future<_i3.MovieDetailResponse> getMovieDetail(int? id) =>
      (super.noSuchMethod(
        Invocation.method(#getMovieDetail, [id]),
        returnValue: _i8.Future<_i3.MovieDetailResponse>.value(
          _FakeMovieDetailResponse_1(
            this,
            Invocation.method(#getMovieDetail, [id]),
          ),
        ),
      ) as _i8.Future<_i3.MovieDetailResponse>);

  @override
  _i8.Future<List<_i13.MovieModel>> getMovieRecommendations(int? id) =>
      (super.noSuchMethod(
        Invocation.method(#getMovieRecommendations, [id]),
        returnValue: _i8.Future<List<_i13.MovieModel>>.value(
          <_i13.MovieModel>[],
        ),
      ) as _i8.Future<List<_i13.MovieModel>>);

  @override
  _i8.Future<List<_i13.MovieModel>> searchMovies(String? query) =>
      (super.noSuchMethod(
        Invocation.method(#searchMovies, [query]),
        returnValue: _i8.Future<List<_i13.MovieModel>>.value(
          <_i13.MovieModel>[],
        ),
      ) as _i8.Future<List<_i13.MovieModel>>);
}

/// A class which mocks [MovieLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieLocalDataSource extends _i1.Mock
    implements _i14.MovieLocalDataSource {
  MockMovieLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<String> insertWatchlist(_i15.MovieTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(#insertWatchlist, [movie]),
        returnValue: _i8.Future<String>.value(
          _i16.dummyValue<String>(
            this,
            Invocation.method(#insertWatchlist, [movie]),
          ),
        ),
      ) as _i8.Future<String>);

  @override
  _i8.Future<String> removeWatchlist(_i15.MovieTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(#removeWatchlist, [movie]),
        returnValue: _i8.Future<String>.value(
          _i16.dummyValue<String>(
            this,
            Invocation.method(#removeWatchlist, [movie]),
          ),
        ),
      ) as _i8.Future<String>);

  @override
  _i8.Future<_i15.MovieTable?> getMovieById(int? id) => (super.noSuchMethod(
    Invocation.method(#getMovieById, [id]),
    returnValue: _i8.Future<_i15.MovieTable?>.value(),
  ) as _i8.Future<_i15.MovieTable?>);

  @override
  _i8.Future<List<_i15.MovieTable>> getWatchlistMovies() => (super.noSuchMethod(
    Invocation.method(#getWatchlistMovies, []),
    returnValue: _i8.Future<List<_i15.MovieTable>>.value(<_i15.MovieTable>[]),
  ) as _i8.Future<List<_i15.MovieTable>>);
}

/// A class which mocks [TVRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVRepository extends _i1.Mock implements _i17.TVRepository {
  MockTVRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i18.TV>>> getOnTheAirTVs() =>
      (super.noSuchMethod(
        Invocation.method(#getOnTheAirTVs, []),
        returnValue: _i8.Future<_i2.Either<_i9.Failure, List<_i18.TV>>>.value(
          _FakeEither_0<_i9.Failure, List<_i18.TV>>(
            this,
            Invocation.method(#getOnTheAirTVs, []),
          ),
        ),
      ) as _i8.Future<_i2.Either<_i9.Failure, List<_i18.TV>>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i18.TV>>> getPopularTVs() =>
      (super.noSuchMethod(
        Invocation.method(#getPopularTVs, []),
        returnValue: _i8.Future<_i2.Either<_i9.Failure, List<_i18.TV>>>.value(
          _FakeEither_0<_i9.Failure, List<_i18.TV>>(
            this,
            Invocation.method(#getPopularTVs, []),
          ),
        ),
      ) as _i8.Future<_i2.Either<_i9.Failure, List<_i18.TV>>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i18.TV>>> getTopRatedTVs() =>
      (super.noSuchMethod(
        Invocation.method(#getTopRatedTVs, []),
        returnValue: _i8.Future<_i2.Either<_i9.Failure, List<_i18.TV>>>.value(
          _FakeEither_0<_i9.Failure, List<_i18.TV>>(
            this,
            Invocation.method(#getTopRatedTVs, []),
          ),
        ),
      ) as _i8.Future<_i2.Either<_i9.Failure, List<_i18.TV>>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, _i19.TVDetail>> getTVDetail(int? id) =>
      (super.noSuchMethod(
        Invocation.method(#getTVDetail, [id]),
        returnValue: _i8.Future<_i2.Either<_i9.Failure, _i19.TVDetail>>.value(
          _FakeEither_0<_i9.Failure, _i19.TVDetail>(
            this,
            Invocation.method(#getTVDetail, [id]),
          ),
        ),
      ) as _i8.Future<_i2.Either<_i9.Failure, _i19.TVDetail>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i18.TV>>> getTVRecommendations(
    int? id,
  ) => (super.noSuchMethod(
    Invocation.method(#getTVRecommendations, [id]),
    returnValue: _i8.Future<_i2.Either<_i9.Failure, List<_i18.TV>>>.value(
      _FakeEither_0<_i9.Failure, List<_i18.TV>>(
        this,
        Invocation.method(#getTVRecommendations, [id]),
      ),
    ),
  ) as _i8.Future<_i2.Either<_i9.Failure, List<_i18.TV>>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, _i20.SeasonDetail>> getTVSeasonDetail(
    int? id,
    int? seasonNumber,
  ) => (super.noSuchMethod(
    Invocation.method(#getTVSeasonDetail, [id, seasonNumber]),
    returnValue: _i8.Future<_i2.Either<_i9.Failure, _i20.SeasonDetail>>.value(
      _FakeEither_0<_i9.Failure, _i20.SeasonDetail>(
        this,
        Invocation.method(#getTVSeasonDetail, [id, seasonNumber]),
      ),
    ),
  ) as _i8.Future<_i2.Either<_i9.Failure, _i20.SeasonDetail>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i18.TV>>> searchTVs(String? query) =>
      (super.noSuchMethod(
        Invocation.method(#searchTVs, [query]),
        returnValue: _i8.Future<_i2.Either<_i9.Failure, List<_i18.TV>>>.value(
          _FakeEither_0<_i9.Failure, List<_i18.TV>>(
            this,
            Invocation.method(#searchTVs, [query]),
          ),
        ),
      ) as _i8.Future<_i2.Either<_i9.Failure, List<_i18.TV>>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, String>> saveWatchlist(
    _i19.TVDetail? tv,
  ) => (super.noSuchMethod(
    Invocation.method(#saveWatchlist, [tv]),
    returnValue: _i8.Future<_i2.Either<_i9.Failure, String>>.value(
      _FakeEither_0<_i9.Failure, String>(
        this,
        Invocation.method(#saveWatchlist, [tv]),
      ),
    ),
  ) as _i8.Future<_i2.Either<_i9.Failure, String>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, String>> removeWatchlist(
    _i19.TVDetail? tv,
  ) => (super.noSuchMethod(
    Invocation.method(#removeWatchlist, [tv]),
    returnValue: _i8.Future<_i2.Either<_i9.Failure, String>>.value(
      _FakeEither_0<_i9.Failure, String>(
        this,
        Invocation.method(#removeWatchlist, [tv]),
      ),
    ),
  ) as _i8.Future<_i2.Either<_i9.Failure, String>>);

  @override
  _i8.Future<bool> isAddedToWatchlist(int? id) => (super.noSuchMethod(
    Invocation.method(#isAddedToWatchlist, [id]),
    returnValue: _i8.Future<bool>.value(false),
  ) as _i8.Future<bool>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i18.TV>>> getWatchlistTVs() =>
      (super.noSuchMethod(
        Invocation.method(#getWatchlistTVs, []),
        returnValue: _i8.Future<_i2.Either<_i9.Failure, List<_i18.TV>>>.value(
          _FakeEither_0<_i9.Failure, List<_i18.TV>>(
            this,
            Invocation.method(#getWatchlistTVs, []),
          ),
        ),
      ) as _i8.Future<_i2.Either<_i9.Failure, List<_i18.TV>>>);
}

/// A class which mocks [TVRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVRemoteDataSource extends _i1.Mock
    implements _i21.TVRemoteDataSource {
  MockTVRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i22.TVModel>> getOnTheAirTVs() => (super.noSuchMethod(
    Invocation.method(#getOnTheAirTVs, []),
    returnValue: _i8.Future<List<_i22.TVModel>>.value(<_i22.TVModel>[]),
  ) as _i8.Future<List<_i22.TVModel>>);

  @override
  _i8.Future<List<_i22.TVModel>> getPopularTVs() => (super.noSuchMethod(
    Invocation.method(#getPopularTVs, []),
    returnValue: _i8.Future<List<_i22.TVModel>>.value(<_i22.TVModel>[]),
  ) as _i8.Future<List<_i22.TVModel>>);

  @override
  _i8.Future<List<_i22.TVModel>> getTopRatedTVs() => (super.noSuchMethod(
    Invocation.method(#getTopRatedTVs, []),
    returnValue: _i8.Future<List<_i22.TVModel>>.value(<_i22.TVModel>[]),
  ) as _i8.Future<List<_i22.TVModel>>);

  @override
  _i8.Future<_i4.TVDetailResponse> getTVDetail(int? id) => (super.noSuchMethod(
    Invocation.method(#getTVDetail, [id]),
    returnValue: _i8.Future<_i4.TVDetailResponse>.value(
      _FakeTVDetailResponse_2(this, Invocation.method(#getTVDetail, [id])),
    ),
  ) as _i8.Future<_i4.TVDetailResponse>);

  @override
  _i8.Future<List<_i22.TVModel>> getTVRecommendations(int? id) =>
      (super.noSuchMethod(
        Invocation.method(#getTVRecommendations, [id]),
        returnValue: _i8.Future<List<_i22.TVModel>>.value(<_i22.TVModel>[]),
      ) as _i8.Future<List<_i22.TVModel>>);

  @override
  _i8.Future<_i5.SeasonDetailResponse> getTVSeasonDetail(
    int? id,
    int? seasonNumber,
  ) => (super.noSuchMethod(
    Invocation.method(#getTVSeasonDetail, [id, seasonNumber]),
    returnValue: _i8.Future<_i5.SeasonDetailResponse>.value(
      _FakeSeasonDetailResponse_3(
        this,
        Invocation.method(#getTVSeasonDetail, [id, seasonNumber]),
      ),
    ),
  ) as _i8.Future<_i5.SeasonDetailResponse>);

  @override
  _i8.Future<List<_i22.TVModel>> searchTVs(String? query) =>
      (super.noSuchMethod(
        Invocation.method(#searchTVs, [query]),
        returnValue: _i8.Future<List<_i22.TVModel>>.value(<_i22.TVModel>[]),
      ) as _i8.Future<List<_i22.TVModel>>);
}

/// A class which mocks [TVLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVLocalDataSource extends _i1.Mock implements _i23.TVLocalDataSource {
  MockTVLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<String> insertWatchlist(_i24.TVTable? tv) => (super.noSuchMethod(
    Invocation.method(#insertWatchlist, [tv]),
    returnValue: _i8.Future<String>.value(
      _i16.dummyValue<String>(this, Invocation.method(#insertWatchlist, [tv])),
    ),
  ) as _i8.Future<String>);

  @override
  _i8.Future<String> removeWatchlist(_i24.TVTable? tv) => (super.noSuchMethod(
    Invocation.method(#removeWatchlist, [tv]),
    returnValue: _i8.Future<String>.value(
      _i16.dummyValue<String>(this, Invocation.method(#removeWatchlist, [tv])),
    ),
  ) as _i8.Future<String>);

  @override
  _i8.Future<_i24.TVTable?> getTVById(int? id) => (super.noSuchMethod(
    Invocation.method(#getTVById, [id]),
    returnValue: _i8.Future<_i24.TVTable?>.value(),
  ) as _i8.Future<_i24.TVTable?>);

  @override
  _i8.Future<List<_i24.TVTable>> getWatchlistTVs() => (super.noSuchMethod(
    Invocation.method(#getWatchlistTVs, []),
    returnValue: _i8.Future<List<_i24.TVTable>>.value(<_i24.TVTable>[]),
  ) as _i8.Future<List<_i24.TVTable>>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i25.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i26.Database?> get database => (super.noSuchMethod(
    Invocation.getter(#database),
    returnValue: _i8.Future<_i26.Database?>.value(),
  ) as _i8.Future<_i26.Database?>);

  @override
  _i8.Future<int> insertWatchlist(_i15.MovieTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(#insertWatchlist, [movie]),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<int> removeWatchlist(_i15.MovieTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(#removeWatchlist, [movie]),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<Map<String, dynamic>?> getMovieById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(#getMovieById, [id]),
        returnValue: _i8.Future<Map<String, dynamic>?>.value(),
      ) as _i8.Future<Map<String, dynamic>?>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getWatchlistMovies() =>
      (super.noSuchMethod(
        Invocation.method(#getWatchlistMovies, []),
        returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
          <Map<String, dynamic>>[],
        ),
      ) as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<int> insertTVWatchlist(_i24.TVTable? tv) => (super.noSuchMethod(
    Invocation.method(#insertTVWatchlist, [tv]),
    returnValue: _i8.Future<int>.value(0),
  ) as _i8.Future<int>);

  @override
  _i8.Future<int> removeTVWatchlist(_i24.TVTable? tv) => (super.noSuchMethod(
    Invocation.method(#removeTVWatchlist, [tv]),
    returnValue: _i8.Future<int>.value(0),
  ) as _i8.Future<int>);

  @override
  _i8.Future<Map<String, dynamic>?> getTVById(int? id) => (super.noSuchMethod(
    Invocation.method(#getTVById, [id]),
    returnValue: _i8.Future<Map<String, dynamic>?>.value(),
  ) as _i8.Future<Map<String, dynamic>?>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getWatchlistTVs() =>
      (super.noSuchMethod(
        Invocation.method(#getWatchlistTVs, []),
        returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
          <Map<String, dynamic>>[],
        ),
      ) as _i8.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i6.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i6.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
        Invocation.method(#head, [url], {#headers: headers}),
        returnValue: _i8.Future<_i6.Response>.value(
          _FakeResponse_4(
            this,
            Invocation.method(#head, [url], {#headers: headers}),
          ),
        ),
      ) as _i8.Future<_i6.Response>);

  @override
  _i8.Future<_i6.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
        Invocation.method(#get, [url], {#headers: headers}),
        returnValue: _i8.Future<_i6.Response>.value(
          _FakeResponse_4(
            this,
            Invocation.method(#get, [url], {#headers: headers}),
          ),
        ),
      ) as _i8.Future<_i6.Response>);

  @override
  _i8.Future<_i6.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i27.Encoding? encoding,
  }) => (super.noSuchMethod(
    Invocation.method(
      #post,
      [url],
      {#headers: headers, #body: body, #encoding: encoding},
    ),
    returnValue: _i8.Future<_i6.Response>.value(
      _FakeResponse_4(
        this,
        Invocation.method(
          #post,
          [url],
          {#headers: headers, #body: body, #encoding: encoding},
        ),
      ),
    ),
  ) as _i8.Future<_i6.Response>);

  @override
  _i8.Future<_i6.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i27.Encoding? encoding,
  }) => (super.noSuchMethod(
    Invocation.method(
      #put,
      [url],
      {#headers: headers, #body: body, #encoding: encoding},
    ),
    returnValue: _i8.Future<_i6.Response>.value(
      _FakeResponse_4(
        this,
        Invocation.method(
          #put,
          [url],
          {#headers: headers, #body: body, #encoding: encoding},
        ),
      ),
    ),
  ) as _i8.Future<_i6.Response>);

  @override
  _i8.Future<_i6.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i27.Encoding? encoding,
  }) => (super.noSuchMethod(
    Invocation.method(
      #patch,
      [url],
      {#headers: headers, #body: body, #encoding: encoding},
    ),
    returnValue: _i8.Future<_i6.Response>.value(
      _FakeResponse_4(
        this,
        Invocation.method(
          #patch,
          [url],
          {#headers: headers, #body: body, #encoding: encoding},
        ),
      ),
    ),
  ) as _i8.Future<_i6.Response>);

  @override
  _i8.Future<_i6.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i27.Encoding? encoding,
  }) => (super.noSuchMethod(
    Invocation.method(
      #delete,
      [url],
      {#headers: headers, #body: body, #encoding: encoding},
    ),
    returnValue: _i8.Future<_i6.Response>.value(
      _FakeResponse_4(
        this,
        Invocation.method(
          #delete,
          [url],
          {#headers: headers, #body: body, #encoding: encoding},
        ),
      ),
    ),
  ) as _i8.Future<_i6.Response>);

  @override
  _i8.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
        Invocation.method(#read, [url], {#headers: headers}),
        returnValue: _i8.Future<String>.value(
          _i16.dummyValue<String>(
            this,
            Invocation.method(#read, [url], {#headers: headers}),
          ),
        ),
      ) as _i8.Future<String>);

  @override
  _i8.Future<_i28.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) => (super.noSuchMethod(
    Invocation.method(#readBytes, [url], {#headers: headers}),
    returnValue: _i8.Future<_i28.Uint8List>.value(_i28.Uint8List(0)),
  ) as _i8.Future<_i28.Uint8List>);

  @override
  _i8.Future<_i6.StreamedResponse> send(_i6.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(#send, [request]),
        returnValue: _i8.Future<_i6.StreamedResponse>.value(
          _FakeStreamedResponse_5(this, Invocation.method(#send, [request])),
        ),
      ) as _i8.Future<_i6.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}
